[project]
name = "odyssey"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "drake>=1.46.0",
    "lcm>=1.5.2",
    "manipulation>=2025.10.20",
]


[build-system]
requires = ["setuptools>=61.0"] # Or your chosen build backend (e.g., poetry, hatch)
build-backend = "setuptools.build_meta" # Or your chosen build backend

[tool.setuptools]
packages = ["odyssey"]