/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcm_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class iiwa_commands_t implements lcm.lcm.LCMEncodable
{
    public long timestamp;
    public double desired_quat[];
    public double desired_pos[];
 
    public iiwa_commands_t()
    {
        desired_quat = new double[4];
        desired_pos = new double[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x49a8924bc8293b23L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcm_msgs.iiwa_commands_t.class))
            return 0L;
 
        classes.add(lcm_msgs.iiwa_commands_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        for (int a = 0; a < 4; a++) {
            outs.writeDouble(this.desired_quat[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.desired_pos[a]); 
        }
 
    }
 
    public iiwa_commands_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public iiwa_commands_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcm_msgs.iiwa_commands_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcm_msgs.iiwa_commands_t o = new lcm_msgs.iiwa_commands_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.desired_quat = new double[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.desired_quat[a] = ins.readDouble();
        }
 
        this.desired_pos = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.desired_pos[a] = ins.readDouble();
        }
 
    }
 
    public lcm_msgs.iiwa_commands_t copy()
    {
        lcm_msgs.iiwa_commands_t outobj = new lcm_msgs.iiwa_commands_t();
        outobj.timestamp = this.timestamp;
 
        outobj.desired_quat = new double[(int) 4];
        System.arraycopy(this.desired_quat, 0, outobj.desired_quat, 0, 4); 
        outobj.desired_pos = new double[(int) 3];
        System.arraycopy(this.desired_pos, 0, outobj.desired_pos, 0, 3); 
        return outobj;
    }
 
}

