"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class iiwa_commands_t(object):
    __slots__ = ["timestamp", "desired_quat", "desired_pos"]

    __typenames__ = ["int64_t", "double", "double"]

    __dimensions__ = [None, [4], [3]]

    def __init__(self):
        self.timestamp = 0
        self.desired_quat = [ 0.0 for dim0 in range(4) ]
        self.desired_pos = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(iiwa_commands_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>4d', *self.desired_quat[:4]))
        buf.write(struct.pack('>3d', *self.desired_pos[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != iiwa_commands_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return iiwa_commands_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = iiwa_commands_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.desired_quat = struct.unpack('>4d', buf.read(32))
        self.desired_pos = struct.unpack('>3d', buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if iiwa_commands_t in parents: return 0
        tmphash = (0x49a8924bc8293b23) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if iiwa_commands_t._packed_fingerprint is None:
            iiwa_commands_t._packed_fingerprint = struct.pack(">Q", iiwa_commands_t._get_hash_recursive([]))
        return iiwa_commands_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", iiwa_commands_t._get_packed_fingerprint())[0]

